apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image: ghcr.io/u1sccl/lab:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: LoadBalancer
  selector:
    app: lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
