name: CI/CD

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Create KIND Cluster
        uses: helm/kind-action@v1

      - name: Deploy to KIND
        run: |
          kubectl apply -f deployment.yaml

      - name: Test
        run: |
          kubectl wait --for=condition=Ready pod -l app=lab --timeout=300s
          NODE_PORT=$(kubectl get svc lab-service -o=jsonpath='{.spec.ports[0].nodePort}')
          NODE_IP=$(kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
          curl -s $NODE_IP:$NODE_PORT
